[phases.setup]
nixPkgs = ["go_1_21"]

[phases.install]
cmds = ["cd backend && go mod download"]

[phases.build]
cmds = ["cd backend && go build -o server ./cmd/server"]

[start]
cmd = "cd backend && ./server"

